name: 猜歌联萌378

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "2 22 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【猜歌联萌378】"
              run: |
                  node /cglm378.js
              env:
                  
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
                  
